version: "2"
checks:
  similar-code:
    enabled: false
plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: "8"
      tests_patterns:
        - pcss-criminal-application/src/test/**/pcsscriminalapplication
  pmd:
    enabled: true
  markdownlint:
    enabled: true
